#!/usr/bin/env python

import signal
import rospy
import yaml
from dev.go_to_specific_point_on_map import GoToPose
from dev.measure_coverage import MeasureAreaCovered

def handler(signum, frmae):
    raise Exception("Unable to reach pose :(")

if __name__ == '__main__':
    print("follow_route running")
    rospy.loginfo("follow_route running")
    # Read information from yaml file
    with open("/home/luis/catkin_ws/src/Turtlebot3_complete_coverage/nodes/route.yaml", 'r') as stream:
        dataMap = yaml.safe_load(stream)

    print("loaded")

    # m = MeasureAreaCovered()
    try:
        # Initialize
        rospy.init_node('follow_route', anonymous=False)
        navigator = GoToPose()

        for obj in dataMap:

            if rospy.is_shutdown():
                break
            name = obj['filename']
            print(obj)
            signal.signal(signal.SIGALRM, handler)
            signal.alarm(15)
            # Navigation
            try:
                rospy.loginfo("Go to %s pose", name[:-4])
                navigator.goto(obj['position'], obj['rotation'])
                rospy.loginfo("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Reached %s pose", name[:-4])
            except Exception as exc:
                print(exc)


        # m.disp()


    except rospy.ROSInterruptException:
        rospy.loginfo("Ctrl-C caught. Quitting")
